name: test

on:
    push:
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                args: ['', '--release']
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              run: rustup update stable && rustup default stable
            - name: Build
              run: cargo build --verbose ${{ matrix.args }}
            - name: Run tests
              run: cargo test --verbose ${{ matrix.args }}
